dist: trusty
language: android
sudo: true
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - python3.5
    - libstdc++-4.9-dev
before_install:
- wget https://dependencies.vcmi.download/android/ext-output.zip
- unzip ext-output.zip
- ". ./CI/android_licenses_fix.sh"
- git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
- export ANDROID_NDK_HOME=$HOME/android-ndk-root
- python3.5 ./CI/create_travis_conf.py
- wget -O ./boost.tar.gz https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz
- mkdir -p ext/boost/
- tar xzvf boost.tar.gz -C ./ext/boost/ >/dev/null
- chmod +x ./project/gradlew
- git submodule update --remote $TRAVIS_BUILD_DIR/ext/vcmi
- python3.5 ./update_internal_assets.py
- echo "y" | sdkmanager "cmake;3.6.4111459"
script:
- python3.5 ./build.py fixpaths
- python3.5 ./build.py build-cmake
- python3.5 ./build.py build-app
after_success:
- ". $TRAVIS_BUILD_DIR/CI/upload_package.sh"
before_deploy:
- git config --local user.name "Zsolt Sz. Sztupak"
- git config --local user.email "mail@sztupy.hu"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: w65UTFweQN4dJLe4EazaDCjFnaP8uf6b4nGGKLRA8PAYTO3M2msudsf9nc0vGHAe+1O2qSIwnM1oihwrJmE1RUQfK4PWcyWwpRWvHK6Swe6PS6kPRBm62pFlcpo+d1ng7DlTQtSZCYv6mp+OBn1NUbElnNtEmCc8HPVtMPH9pIL27DZi47PxRHyg0uMo03wlEc9gwRpP/1M9PWAPBJgK75sGfkA1QAioEWduBg2tvrHhT9qO1nLGaKWC36IVX8QwdpQde3jFTvmhZqEyUHazsuzHCgXbRI2eTWfRqtLvaPX5tjTUFRSDtf9N/cFyrzZXW8EKFlD+pSQ8AL3Ugpg7x/0qgrTBNjlU+R0xxeTCAhCgdabGEyutUCeYLmjcNTFroGjuSXdoVOrfbOyNaOv7pOSwGG6uoF3trY/dTJq1yn/sEc9SuutAHLFApWga5AwesVtFS2idKwrugKNaGQ5qpoDhlHIV+ESAGK0GgmZCKEWioDpBKvbGiJEiDV6Adbps83FvyjNBuQYIvuZVz7EcqnMxlkY5/2OGbfTiBn4jlBxgNPVvabcCZ7bOnMUNOVnZ0XYaA9BG6PkFxO6oNKZ8CXBdEpC6jcLTU9hwdkAHHgWFvtmKz+zfeW6BbuJyak8/eA9ZvNTGyxnW6FRIQ/+j65GuPWd5AxqitY8eYR3n/7I=
  file: vcmi.apk
  draft: true
  skip_cleanup: true
  on:
    repo: sztupy/vcmi-android
